### ISSUE TITLE
アホほどおもい

### ISSUE THREAD

**Issue by nabr2730** [NamagomiNetwork/Namagomi-mod#63]
![image](https://user-images.githubusercontent.com/100725601/173623020-7e9f0a5f-61a4-4a0d-9539-ba5c3759023b.png)

なんなんですかこれ
(ちなみに8GB割当)

**Comment by yuuki1293** [comment]
サーバーに参加する場合6GB

**Comment by nabr2730** [comment]
> サーバーに参加する場合6GB

ちなみにすぐ8GBになる()

**Comment by yuuki1293** [comment]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/71992891/173630257-4f2e2002-f097-4374-ade6-3e14fed94654.png">  
-Xmx4G の場合

**Comment by nabr2730** [comment]
とりあえずヒープダンプ解析します

**Comment by nabr2730** [comment]
#70 で改善
