### ISSUE TITLE
mod追加要望 Environmental Tech

### ISSUE THREAD

**Issue by yuuki1293** [NamagomiNetwork/Namagomi-mod#67]
Mod名: Environmental Tech
Modのバージョン: 2.0.20.1
DL先: https://www.curseforge.com/minecraft/mc-mods/environmental-tech/files/2691536
前提: https://www.curseforge.com/minecraft/mc-mods/valkyrielib/files/2691542
説明: 
- 主に電力を使用して岩盤か奈落から鉱石、植物、資源を無限に生成する機械を追加
メリット: 
- ルートテーブルへの鉱石の追加はconfigファイルを書き換えるだけ
- 広範囲を探索する必要がなくなるため軽くなる
- 鉱石生成が追加されるmodでも後からの導入が容易になる
- 「砂鉄集めるのめんどくせーーーーー」を解決

**Comment by TONKATZ** [comment]
追加完了
