### ISSUE TITLE
AE2の隕石生成をなくし、代替レシピを追加する

### ISSUE THREAD

**Issue by yuuki1293** [NamagomiNetwork/Namagomi-mod#74]

**Comment by yuuki1293** [comment]
<img width="186" alt="image" src="https://user-images.githubusercontent.com/71992891/173994726-572eaf0f-2383-48ef-b312-bb65edd40a5a.png">
スカイストーン

**Comment by yuuki1293** [comment]
<img width="184" alt="image" src="https://user-images.githubusercontent.com/71992891/173994780-e33deca2-e8f9-484e-903e-970d33d3e986.png">
Inscriber Calculation Press

**Comment by yuuki1293** [comment]
<img width="183" alt="image" src="https://user-images.githubusercontent.com/71992891/173994900-ea9a26f5-fe66-487a-9413-b1b035e8cf4d.png">
Inscriber Engineering Press

**Comment by yuuki1293** [comment]
<img width="182" alt="image" src="https://user-images.githubusercontent.com/71992891/173995007-ba2418a7-c1dc-4cd2-9330-7d714db9b3ab.png">
Inscriber Logic Press

**Comment by yuuki1293** [comment]
<img width="182" alt="image" src="https://user-images.githubusercontent.com/71992891/173995066-f1eaf8a9-1c31-43af-a24f-39d122077b09.png">
Inscriber Silicon Press

**Comment by TONKATZ** [comment]
スカイストーンの真ん中のやつってなんですか

**Comment by yuuki1293** [comment]
隕石コンパスです

**Comment by yuuki1293** [comment]
<img width="183" alt="image" src="https://user-images.githubusercontent.com/71992891/174003202-48a5eb4d-e13b-4ca6-aac8-9923140e667b.png">

**Comment by yuuki1293** [comment]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/71992891/174003264-b3d7cac2-c622-46f4-a21d-4c23a1447885.png">

**Comment by TONKATZ** [comment]
なるほどね

**Comment by yuuki1293** [comment]
金型はMysticalAgricultureの方ですでにレシピがあったのでそれで
